apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
spec:
  type: openapi
  owner: user:SreeHarshithaGaddam
  definition:
    $text: ./petstore.oas.yaml
