apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testing_type
  description: The petstore API
  tags:
    - store
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: user:SreeHarshithaGaddam
  definition: "no version"
